name: Events Demo 1

on:
  pull_request:
    types: 
      - opened
      - closed
    branches:
      - main # we have to give target branch
    paths-ignore:
      - '.github/workflows/*'
  workflow_dispatch:
  push:
    branches:
      - SRE-*
      - features/*
    # paths-ignore:
    #   - '.github/workflows/*'

jobs:
  build-and-upload:
    outputs:
      js_file: ${{ steps.publish.outputs.filename }}
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test
      - name: Build code
        run: npm run build
      - name: Output the js filename
        id: publish
        run: find dist/assets/*.js -type f -execdir echo 'filename={}' >> $GITHUB_OUTPUT ';'
      - name: Upload code
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: |
            dist
            package.json
  deploy:
    needs:
      build-and-upload
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"
      - name: Deploy project
        run: echo "Deploying..."
  download-artifacts:
    needs:
      build-and-upload
    runs-on: ubuntu-latest
    steps:
      - name: output the js file name
        run: echo "${{ needs.build-and-upload.outputs.js_file }}"
      - name: show downloaded artifacts
        run: ls -ltr
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: dist-files
      - name: show downloaded artifacts
        run: ls -ltr
